# Generated by Django 4.1.2 on 2022-11-01 08:24

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='article',
            field=models.TextField(blank=True, default='контент'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('newblock', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(blank=True)), ('info', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())]))], blank=True, use_json_field=None),
        ),
    ]
